name: Hello World

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
  terraform-validate:
    name: terraform validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/backend-bootstrap
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        run: terraform init -backend=false
      - name: Terraform validate
        run: terraform validate

    